string RED="Red"          # Selects which table the robot will pick trays from
string GREEN="Green"
string BLUE="Blue"
string ORANGE="Orange"
string PURPLE="Purple"

string BATTERY="Battery"
string PUMP="Pump"
string SENSOR="Sensor"
string REGULATOR="Regulator"

string QUADRANT1="1"
string QUADRANT2="2"
string QUADRANT3="3"
string QUADRANT4="4"

string TRAY1="1"
string TRAY2="2"
string TRAY3="3"
string TRAY4="4"

string part_color   # Part color to be transported by robot
string part_type    # Part type to be transported by robot
string quadrant_id   # Quadrant to place or take part form
string tray_id 

