string TABLE1="1"          # Selects which table the robot will pick trays from
string TABLE2="2"

string TRAY_ONE="1"
string TRAY_TWO="2"
string TRAY_THREE="3"
string TRAY_FOUR="4"

string AGV1="1"
string AGV2="2"
string AGV3="3"
string AGV4="4"

string TRAY1="1"
string TRAY2="2"
string TRAY3="3"
string TRAY4="4"

string tray_id   # Tray transported by robot
string table     # Location of table tray is placed or picked up from   
string agv_id    # Agv tray will be placed to and picked up from